# Generated by Django 3.1.1 on 2020-09-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя тега')),
                ('tag_table', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Таблица тегов')),
                ('data_type', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Тип данных')),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес в памяти')),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Комментарий')),
                ('group', models.ForeignKey(db_column='name_group', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.group')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
