# Generated by Django 3.1.1 on 2020-09-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='group',
            name='name_group',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Группа тегов'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='group',
            field=models.ForeignKey(db_column='name_group', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.group', verbose_name='Группа тегов'),
        ),
    ]
