# Generated by Django 3.1.5 on 2021-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20200912_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='comment',
            field=models.CharField(blank=True, default='No comment', max_length=100, null=True, verbose_name='Комментарий'),
        ),
    ]
