# Generated by Django 3.1.5 on 2021-01-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20210110_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Комментарий'),
        ),
    ]
